export const SCHEME_PREFS = {
	UNSUPPORTED: 0,
	NO_PREFERENCE: 1,
	DARK: 2,
	LIGHT: 3,
	CUSTOM_ONE: 4,
	CUSTOM_TWO: 5,
	CUSTOM_THREE: 6
}
export const MOTION_PREFS = {
	UNSUPPORTED: 0,
	NO_PREFERENCE: 1,
	REDUCE: 2
}
export const CONTRAST_PREFS = {
	NO_PREFERENCE: 0,
	MORE: 1,
	LESS: 2
}
